### ISSUE TITLE
chunk_pos type wrong

### ISSUE THREAD

**Issue by 2qif49lt** [starship-technologies/bag_rdr#1]
https://github.com/starship-technologies/bag_rdr/blob/master/bag_rdr.cpp#L659

 common::optional<int32_t>  chunk_pos will be wrong with big file.

should be  common::optional<int64_t>. and also  as [http://wiki.ros.org/Bags/Format/2.0#Chunk_info](http://wiki.ros.org/Bags/Format/2.0#Chunk_info) describe it's 8 bytes

**Comment by lsr0** [comment]
Thanks, and apologies I missed this. Merged your change from lukehutch's PR #2
